Adjustment of the Create, Get and GetById methods and creation of the…
Okaada/back-app-sr pull request #11
Opened 2024-08-18 16:20 UTC by DiyowRocha

… Update and Delete methods

2024-08-18 21:09 UTC, Okaada requested changes
alguns ajustes por ae eheheheheh

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Command/CreateItem/CreateItemCommand.cs
> +    public bool Active { get; set; } = true;
ppropriedades booleanas são mais interessantes se começarem com o o prefixo Is, Can ou Has, outro ponto sobre essa propriedade estará adicionado em outro comentário

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Command/CreateItem/CreateItemValidator.cs
> +        RuleFor(x => x.Active).Must(active => active == true).WithMessage("O item deve estar ativo para ser criado.");
Remover, essa linha

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Query/GetActiveItemById/GetActiveItemByIdQuery.cs
> +    public bool Active { get; set; }
Ajustar prefixo da variável

2024-08-18 21:09 UTC, Okaada commented on back-app-sr.Domain/Models/Items/ItemModel.cs
> +    public bool Active { get; set; }
ajustar prefixo

2024-08-18 21:09 UTC, Okaada commented on back-app-sr.Domain/Models/Items/ItemModel.cs
> +        Active = active;
existe uma melhoria que pode ser aplicada nessa atribuição de valor, vou deixar você dar uma pesquisada nesse caso para enxergar talvez um pouco mais abrangente a função do constructor da classe. qualquer coisa manda no whats se travar a cabeça

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +    public async Task<DeleteItemViewModel> DeleteItem(int id)
esse nome não está em acordo ao que o método do faz, ajustar para DeactivateItem

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +    public async Task<GetItemViewModel> GetActiveItemById(int itemId)
Aqui todos os itens estão sendo obtidos. o nome do método tem que condizer com o que ele faz, mesmo que para o front os itens que são retornados são apenas os ativos (num caso hipotético) o back está trazendo todos do banco

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +    public async Task<GetItemViewModel> GetActiveItemById(int itemId)
sugestão: ou ajustar o nome do método ou entender o uso de LINQ Expression para retornar apenas itens ativos

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Query/GetAllActiveItems/GetAllActiveItemsQueryHandler.cs
> +        return activeItems;
falando sobre um outro comentário, você ja pesquisou sobre LINQ, no entanto o ajuste é valido... o Get que a service faz basicamente está buscando todo com o nome GetActiveItem... isso pode gerar confusão

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Query/GetActiveItemById/GetActiveItemByIdQueryHandler.cs
> +            throw new Exception();
se active item == null ou item == false, não deveria retornar exception, talvez retornar um objeto vazio tipo um new GetItemViewModel(); e na controller vc faz a validação pra ver se item.Name contem valor, e caso não retorna um 204 pro front

2024-08-18 21:09 UTC, Okaada commented on back-app-sr.WebApi/Controllers/ItemController.cs
> +    public async Task<IActionResult> DeleteItem([FromRoute] int id)
se esse for a exclusão lógica, é mais ideal que seja um put, caso enxerguemos necessidade de adicionar um DELETE real do banco, ai adicionamos o verbo correto da api REST

2024-08-18 21:09 UTC, Okaada commented on back-app-sr.WebApi/Controllers/ItemController.cs
> +            return BadRequest("ID no URL não corresponde ao ID no corpo da requisição.");
aqui existe uma questão, entendo o motivo de você ter enxergado dessa maneira, mas já que o id está sendo passado via route, não precisa ser enviado de novo por meio de body
e tambem entendo que eu poderia ter enxergado isso no primeiro pr

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/ViewModel/UpdateItemViewModel.cs
> +    public bool Active { get; set; }
ajustar nome

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/ViewModel/GetItemViewModel.cs
> +    public bool Active { get; set; }
ajustar nome

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/ViewModel/DeleteItemViewModel.cs
> +}
entender necessidade dessa view model

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +            throw new Exception("Não é possível atualizar um item inativo");
Porque não?

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +            throw new Exception("Item não encontrado");
se não for encontrado não precisa dar esse "alarme" de exception, https://tiagotartari.net/exceptions-para-validar-o-dominio-certo-ou-errado.html#:~:text=As%20exceptions%20são%20usadas%20para,tipos%20de%20exceptions%20predefinidas%20no%20.

2024-08-18 21:09 UTC, Okaada commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +            throw new Exception("Item não encontrado");
revisar outros casos também

2024-08-19 22:53 UTC, Okaada commented on back-app-sr-Application/Item/Command/UpdateItem/UpdateItemCommand.cs
> +    [JsonProperty("item_id")]
o id ja é recebido através da rota, sem necessidade de adicionar uma json prop pra ele

2024-08-20 21:33 UTC, DiyowRocha commented on back-app-sr-Application/Item/Command/CreateItem/CreateItemCommand.cs
> +    public bool Active { get; set; } = true;
Alterado para IsActive

2024-08-20 21:33 UTC, DiyowRocha commented on back-app-sr-Application/Item/Command/CreateItem/CreateItemValidator.cs
> +        RuleFor(x => x.Active).Must(active => active == true).WithMessage("O item deve estar ativo para ser criado.");
Linha removida

2024-08-20 21:36 UTC, DiyowRocha commented on back-app-sr-Application/Item/Query/GetActiveItemById/GetActiveItemByIdQuery.cs
> +    public bool Active { get; set; }
Propriedade Active removida

2024-08-20 21:36 UTC, DiyowRocha commented on back-app-sr.Domain/Models/Items/ItemModel.cs
> +    public bool Active { get; set; }
Alterada para IsActive

2024-08-20 21:37 UTC, DiyowRocha commented on back-app-sr.Domain/Models/Items/ItemModel.cs
> +        Active = active;
Alterada a responsabilidade para o construtor da classe

2024-08-20 21:39 UTC, DiyowRocha commented on back-app-sr-Application/Item/ViewModel/UpdateItemViewModel.cs
> +    public bool Active { get; set; }
Alterado para IsActive

2024-08-20 21:39 UTC, DiyowRocha commented on back-app-sr-Application/Item/ViewModel/GetItemViewModel.cs
> +    public bool Active { get; set; }
Alterado para IsActive

2024-08-20 21:40 UTC, DiyowRocha commented on back-app-sr-Application/Item/ViewModel/DeleteItemViewModel.cs
> +}
Função delete será implementada de forma correta, viewModel vai retornar somente nome

2024-08-20 21:42 UTC, DiyowRocha commented on back-app-sr-Application/Item/Command/UpdateItem/UpdateItemCommand.cs
> +    [JsonProperty("item_id")]
Alterei para JsonIgnore e vou revisar o método Update

2024-08-20 21:43 UTC, DiyowRocha commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +            throw new Exception("Não é possível atualizar um item inativo");
Revisei a lógica

2024-08-20 21:44 UTC, DiyowRocha commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +    public async Task<DeleteItemViewModel> DeleteItem(int id)
Esse é outro caso que vou revisar para implementar o Delete de forma correta

2024-08-20 21:45 UTC, DiyowRocha commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +    public async Task<GetItemViewModel> GetActiveItemById(int itemId)
Alterado o nome do método para GetItemById

2024-08-20 21:46 UTC, DiyowRocha commented on back-app-sr.WebApi/Controllers/ItemController.cs
> +            return BadRequest("ID no URL não corresponde ao ID no corpo da requisição.");
Alterado para envio via DTO, utilizando o ID vindo da rota

2024-08-20 23:59 UTC, DiyowRocha commented on back-app-sr-Application/Item/Service/Implementation/ItemService.cs
> +            throw new Exception("Item não encontrado");
Ajustado para retornar viewModel vazia

2024-08-21 00:01 UTC, DiyowRocha commented on back-app-sr-Application/Item/Query/GetAllActiveItems/GetAllActiveItemsQueryHandler.cs
> +        return activeItems;
Ajustado para GetAllItems

2024-08-21 00:01 UTC, DiyowRocha commented on back-app-sr.WebApi/Controllers/ItemController.cs
> +    public async Task<IActionResult> DeleteItem([FromRoute] int id)
Removido

2024-08-21 15:22 UTC, DiyowRocha commented on back-app-sr-Application/Item/Query/GetActiveItemById/GetActiveItemByIdQueryHandler.cs
> +            throw new Exception();
Ajustado para retornar objeto vazio

2024-08-21 22:55 UTC, Okaada approved these changes

2024-08-21 22:55 UTC, merged